# Generated by Django 5.1.7 on 2025-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
