# Generated by Django 5.1.7 on 2025-03-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='addresses',
        ),
    ]
